restaurant_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from booking import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.get_booking_list, kwargs=None, name='get_booking_list'),
    path('add_booking', views.add_booking, name='add_booking'),
    path('edit/<bookingItem_id>', views.edit_booking, name='edit_booking'),
    path('delete/<bookingItem_id>',
         views.delete_booking, name='delete_booking'),
]

booking/models.py
from django.db import models

# Create your models here.


class bookingItem(models.Model):
    name = models.CharField(max_length=49, null=False, blank=False)
    time = models.TimeField(auto_now=False, auto_now_add=False,
                            null=False, blank=False)
    adultNum = models.DecimalField(max_digits=2, decimal_places=0,
                                   null=False, blank=False)
    date = models.DateField(auto_now=False, auto_now_add=False,
                            null=False, blank=False)
    childNum = models.DecimalField(max_digits=2, decimal_places=0,
                                   null=False, blank=False)
    highChair = models.DecimalField(max_digits=1, decimal_places=0,
                                    null=False, blank=False)
    roomNum = models.DecimalField(max_digits=3, decimal_places=0,
                                  null=False, blank=False)
    comment = models.CharField(max_length=199, null=False, blank=False)
    email = models. EmailField(max_length=254, null=False, blank=True)

    def __str__(self):
        return self.name

booking/forms.py
from django import forms
from .models import bookingItem


class bookingItemForm(forms.ModelForm):
    class Meta:
        model = bookingItem
        fields = ['name', 'roomNum', 'date', 'time', 'adultNum', 'childNum',
                  'highChair', 'comment', 'email']
        widgets = {
            'date': forms.DateInput(attrs={'class': 'date',
                                    'placeholder': 'Only this format! 2020-07-26'},
                                    format='%Y-%m-%d'),
            'time': forms.TimeInput(attrs={'class': 'time',
                                    'placeholder': 'Only this format! 18:30'})
        }

booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import bookingItem
from .forms import bookingItemForm

# Create your views here.


def get_booking_list(request):
    BookingItems = bookingItem.objects.all()
    context = {
        'BookingItems': BookingItems
    }
    return render(request, 'booking/booking_list.html', context)


def add_booking(request):
    if request.method == 'POST':
        form = bookingItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('get_booking_list')

    form = bookingItemForm()
    context = {
        'form': form
    }
    return render(request, 'booking/add_booking.html', context)


def edit_booking(request, bookingItem_id):
    item = get_object_or_404(bookingItem, id=bookingItem_id)
    if request.method == 'POST':
        form = bookingItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('get_booking_list')
    form = bookingItemForm(instance=item)
    context = {
        'form': form
    }
    return render(request, 'booking/edit_booking.html', context)


def delete_booking(request, bookingItem_id):
    item = get_object_or_404(bookingItem, id=bookingItem_id)
    item.delete()
    return redirect('get_booking_list')

booking/templates/booking/add_booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
</head>
<body>
    <h1>Add New Bookings</h1>

    <form method="POST" action="add_booking">
       {% csrf_token %}
    
       <div>
       
          <p>
          
          <label for="id_name">Name: </label>
          <input type="text" id="id_name" name="booking_name">
          
          </p>

       </div>

       <div>
          <p>
          <button type="submit">Add Booking</button>
          </p>
       </div>
    </form>
</body>
</html>

booking/templates/booking/booking_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
</head>
<body>
    <h1>Restaurant Booking</h1>
    <a href="/add_booking"> Create New Booking</a>
    
    <table>
       {% for item in BookingItems %}
          <tr>
             <td>Booking Name: {{ item.name }}</td>
          </tr>
          <tr>
            <td>Booking Date: {{ item.date }}</td>
          </tr>
          <tr>
            <td>Booking Time: {{ item.time }}</td>
          </tr>
          <tr>
           <td>Number of Adults: {{ item.adultNum }}</td>
          </tr>
          <tr>
           <td>Number of Children: {{ item.childNum }}</td>
          </tr>
          <tr>
           <td>Number of High Chair req.: {{ item.highChair }}</td>
          </tr>
          <tr>
           <td>Room number: {{ item.roomNum }}</td>
          </tr>
          <tr>
           <td>Comment: {{ item.comment }}</td>
          </tr>
          <tr>
           {% if item.email %}
           <td>Email: {{ item.email }}</td>
           {% else %}
           <td>No email given.</td>
           {% endif %}
           <td>
           
             <a href="/edit/{{ item.id }}">
             
                 <button>Edit</button>
             </a>
           
           </td>
           <td>
           
             <a href="/delete/{{ item.id }}">
             
                 <button>Delete</button>
             </a>
           
           </td>
          </tr>
       {% endfor %}
    </table>
</body>
</html>

booking/templates/booking/edit_booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
</head>
<body>
    <h1>Edit Bookings</h1>

    <form method="POST">
       {% csrf_token %}
       {{ form.as_p }}

       <div>
          <p>
          <button type="submit">Update Booking</button>
          </p>
       </div>
    </form>
</body>
</html>